package com.example.demo.DataSource;

import org.springframework.boot.autoconfigure.jdbc.DataSourceProperties;
import org.springframework.boot.jdbc.EmbeddedDatabaseConnection;
import org.springframework.util.StringUtils;

public class EventuallyEmbeddedDataSourceProperties extends DataSourceProperties {

    /**
     * Overriding method because as of Spring 3.1.4 version, the database name is autogenerated, which produces
     * conflicts when more than one datasource is provided, even if they pointed at the same database on the properties
     *
     */
    @Override
    public String determineDatabaseName() {
        if (StringUtils.hasLength(super.getName())) {
            return super.getName();
        } else {
            return super.getEmbeddedDatabaseConnection() != EmbeddedDatabaseConnection.NONE ? "testdb" : null;
        }
    }
}
